### ISSUE TITLE
Customize the text color of the button

### ISSUE THREAD

**Issue by googol7** [abdurrahman720/react-swipeable-button#4]
It would be great if you could specify the color for the text of the button.

Currently, it is hard coded [here](https://github.com/abdurrahman720/react-swipeable-button/blob/main/src/components/SwipeableButton.css#L134):

```css
.rsbcText {
  color: #000;
}
```
